# backend-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            serviceAccountName: solar-car-sa
            containers:
                - name: backend
                  image: gcr.io/solarcaroncloud/backend:latest
                  ports:
                      - containerPort: 5000
                  env:
                      - name: GOOGLE_APPLICATION_CREDENTIALS
                        value: "/var/secrets/google/key.json"
                  volumeMounts:
                      - name: google-cloud-credentials
                        mountPath: /var/secrets/google
                        readOnly: true
            volumes:
                - name: google-cloud-credentials
                  secret:
                      secretName: google-cloud-credentials
---
apiVersion: v1
kind: Service
metadata:
    name: backend-service
spec:
    type: LoadBalancer
    loadBalancerIP: 35.226.184.53
    ports:
        - port: 5000
    selector:
        app: backend
