# frontend-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend
                  image: gcr.io/solarcaroncloud/frontend:latest
                  ports:
                      - containerPort: 80
                  volumeMounts:
                      - name: nginx-config-volume
                        mountPath: /etc/nginx/nginx.conf
                        subPath: nginx.conf
            volumes:
                - name: nginx-config-volume
                  configMap:
                      name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
    name: frontend-service
spec:
    type: LoadBalancer
    ports:
        - port: 80
    selector:
        app: frontend
