name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v2
              with:
                  project_id: solarcaroncloud
                  service_account_key: ${{ secrets.GCP_SA_KEY }}
                  export_default_credentials: true
                  install_components: "beta"

            # Authenticate Docker to Google Container Registry
            - name: Authenticate Docker to Google Cloud Registry
              run: |
                  gcloud auth configure-docker gcr.io --quiet

            - name: Check GCP authentication
              run: |
                  gcloud auth list
                  gcloud config list project

            - name: Build and push Backend image
              run: |
                  cd Backend
                  docker build -f Dockerfile -t gcr.io/solarcaroncloud/backend:latest .
                  docker push gcr.io/solarcaroncloud/backend:latest

            - name: Build and push Frontend image
              run: |
                  cd Frontend
                  docker build -f Dockerfile -t gcr.io/solarcaroncloud/frontend:latest .
                  docker push gcr.io/solarcaroncloud/frontend:latest

            - name: Build and push Data-Sender image
              run: |
                  cd Data-Sender
                  docker build -f Dockerfile -t gcr.io/solarcaroncloud/data-sender:latest .
                  docker push gcr.io/solarcaroncloud/data-sender:latest

            - name: Set up kubectl
              uses: azure/setup-kubectl@v1
              with:
                  version: "latest"

            - name: Get GKE credentials
              run: |
                  gcloud container clusters get-credentials sensor-cluster --region us-central1-a --no-enable-gke-gcloud-auth-plugin

            - name: Deploy Backend
              run: |
                  kubectl apply -f backend-deployment.yaml

            - name: Deploy Frontend
              run: |
                  kubectl apply -f frontend-deployment.yaml

            - name: Deploy Data-Sender
              run: |
                  kubectl apply -f sender-deployment.yaml

            - name: Clean up
              run: |
                  rm ${HOME}/gcp-key.json
