name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v2
              with:
                  project_id: solarcaroncloud
                  service_account_key: ${{ secrets.GCP_SA_KEY }}
                  export_default_credentials: true
                  install_components: "beta"

            # Authenticate Docker to Google Container Registry
            - name: Authenticate Docker to Google Cloud Registry
              run: |
                  gcloud auth configure-docker gcr.io

            - name: Check GCP authentication
              run: |
                  gcloud auth list
                  gcloud config list project

            - name: Build Docker images
              run: |
                  docker build -t gcr.io/solarcaroncloud/backend ./Backend
                  docker build -t gcr.io/solarcaroncloud/frontend ./Frontend
                  docker build -t gcr.io/solarcaroncloud/sender ./Data-Sender

            - name: Push Docker images to Google Container Registry
              run: |
                  docker push gcr.io/solarcaroncloud/backend
                  docker push gcr.io/solarcaroncloud/frontend
                  docker push gcr.io/solarcaroncloud/sender

            - name: Set up kubectl
              uses: azure/setup-kubectl@v1
              with:
                  version: "latest"

            - name: Get GKE credentials
              run: |
                  gcloud container clusters get-credentials sensor-cluster --region us-central1-a --no-enable-gke-gcloud-auth-plugin

            - name: Deploy to Kubernetes
              run: |
                  kubectl apply -f backend-deployment.yaml
                  kubectl apply -f frontend-deployment.yaml
                  kubectl apply -f sender-deployment.yaml

            - name: Clean up
              run: |
                  rm ${HOME}/gcp-key.json
