name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v2
              with:
                  project_id: solarcaroncloud
                  version: "latest"

            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v0.5.0
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}

            - name: Authenticate Docker to Google Cloud Registry
              run: |
                  gcloud auth configure-docker

            - name: Check GCP authentication
              run: |
                  gcloud auth list
                  gcloud config list project

            - name: Build Docker images
              run: |
                  docker build -t gcr.io/solarcaroncloud/backend ./Backend
                  docker build -t gcr.io/solarcaroncloud/frontend ./Frontend
                  docker build -t gcr.io/solarcaroncloud/sender ./Data-Sender

            - name: Push Docker images to Google Container Registry
              run: |
                  docker push gcr.io/solarcaroncloud/backend
                  docker push gcr.io/solarcaroncloud/frontend
                  docker push gcr.io/solarcaroncloud/sender

            - name: Set up kubectl
              uses: azure/setup-kubectl@v4

            - name: Get GKE credentials
              run: |
                  gcloud container clusters get-credentials sensor-cluster --region us-central1-a

            - name: Install gke-gcloud-auth-plugin
              run: |
                  gcloud components install gke-gcloud-auth-plugin

            - name: Deploy to Kubernetes
              run: |
                  kubectl apply -f backend-deployment.yaml
                  kubectl apply -f frontend-deployment.yaml
                  kubectl apply -f sender-deployment.yaml
